AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Step Functions - State Machine
Resources:
  StateMachineComponent:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: EchoInput
      DefinitionString: |-
        {
          "StartAt": "MyPassState",
          "States": {
            "MyPassState": {
              "Type": "Pass",
              "Next": "Wait for 3 seconds"
            },
            "Wait for 3 seconds": {
              "Seconds": 3,
              "Type": "Wait",
              "Next": "Convert HelloWorld to Base64"
            },
            "Echo Input to Output": {
              "Parameters": {
                "FunctionName": "EchoInput",
                "Payload": {
                  "input": "Hello, world!"
                }
              },
              "Resource": "arn:aws:states:::lambda:invoke",
              "Type": "Task",
              "End": true,
              "Retry": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "IntervalSeconds": 15,
                  "MaxAttempts": 2,
                  "BackoffRate": 4.0
                }
              ],
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "LambdaTaskFailed"
                }
              ]
            },
            "LambdaTaskFailed": {
              "Type": "Fail"
            }
          }
        }
      RoleArn: arn:aws:iam::111111111111:role/MyRole
